[project]
authors = [
    {name = "James Demetris"},
]
name            = "personal-python-ast-optimizer"
version         = "1.1.3"
readme          = "README.md"
requires-python = ">=3.10"
dependencies = [
  "autoflake==2.3.1"
]
